name: Update Total Contributions

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    # Add this permissions block
    permissions:
      contents: write # Grants write permissions for repository content

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Total Contributions
        id: get_contributions
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          USERNAME: IMOitself
        run: |
          # Get user creation year
          creation_year=$(curl -s -H "Authorization: bearer $GH_PAT" -X POST -d '{ "query": "query { user(login: \"'$USERNAME'\") { createdAt } }" }' https://api.github.com/graphql | jq -r '.data.user.createdAt' | cut -d'-' -f1)
          current_year=$(date +'%Y')
          total_contributions=0

          for year in $(seq $creation_year $current_year); do
            from_date="${year}-01-01T00:00:00Z"
            to_date="${year}-12-31T23:59:59Z"

            query='{"query": "query ($from: DateTime!, $to: DateTime!) { user(login: \"'$USERNAME'\") { contributionsCollection(from: $from, to: $to) { contributionCalendar { totalContributions } } } }", "variables": {"from": "'$from_date'", "to": "'$to_date'"}}'
            contributions=$(curl -s -H "Authorization: bearer $GH_PAT" -X POST -d "$query" https://api.github.com/graphql | jq '.data.user.contributionsCollection.contributionCalendar.totalContributions')

            total_contributions=$((total_contributions + contributions))
          done

          echo "total_contributions=$total_contributions" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -E -i "s/.*❤️([^:]+): .* total/❤️\1: ${{ env.total_contributions }} total/" README.md

      - name: Check for staged changes
        id: check_changes
        run: |
          git add . # Or your specific file_pattern
          if git diff --staged --quiet; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: |
            docs: update total contributions
          file_pattern: README.md
          commit_author: IMOaswell <IMOaswell@users.noreply.github.com>
